import fs from 'fs';
let content = fs.readFileSync('scripts/fetch-books.mjs', 'utf8');

content = content.replace(
  /<span class="vol-badge">\$\{typeof vol\.volNum === 'number' \? `第\$\{vol\.volNum\}巻` : vol\.volNum\}<\/span>\n/g,
  ''
);

content = content.replace(
  /\.vol-badge\{position:absolute;top:4px;left:4px;background:#17221f;color:#fff;font-size:10px;padding:2px 6px;border-radius:3px;font-weight:bold\}/g,
  ''
);

const newStyleMedia = `@media(max-width:600px){.cover-main{width:130px;height:180px;margin-left:16px}.vol-shelf-grid{grid-template-columns:repeat(3,1fr);gap:10px}.work-detail-main{display:flex;flex-direction:column}.wd-vols{order:3;margin-top:32px}.wd-rest{order:2}}`;

content = content.replace(
  /@media\(max-width:600px\)\{\.cover-main\{width:130px;height:180px;margin-left:16px\}\.vol-shelf-grid\{grid-template-columns:repeat\(3,1fr\);gap:10px\}\}/g,
  newStyleMedia
);

const oldBody = `<main><div class="crumb"><a href="/">トップ</a>　/　<a href="/works/">作品一覧</a>　/　作品詳細</div><img class="cover-main" src="\${escapeXml(book.cover)}" alt="\${escapeXml(book.title)}の表紙"><div class="eyebrow">WORK GUIDE & REVIEW</div><h1>\${escapeXml(book.title)}</h1><p>作者：<a href="/authors/\${slugify(book.author)}/">\${escapeXml(book.author)}</a>　｜　\${escapeXml(book.genre)}　｜　最新発売日：\${escapeXml(book.salesDate)}</p><p style="font-size:16px;line-height:1.9;color:#3d4841;">\${escapeXml(book.aiIntro || book.description)}</p><a class="cta" href="\${escapeXml(book.affiliateUrl)}" rel="sponsored nofollow noopener" target="_blank">【無料試し読みあり】1巻を楽天Koboで購入 ↗</a><div class="pub-status-box"><div class="pub-status-main"><h3>📢 最新刊・次巻の出版予定日ステータス</h3><p>最新巻：絶賛配信中！ / 次巻（続巻）：<b>2026年秋頃出版予定（公式発表待ち）</b></p></div><a style="background:#d6a24a;color:#17221f;padding:10px 18px;border-radius:4px;font-weight:bold;text-decoration:none;font-size:13px;" href="\${escapeXml(book.affiliateUrl)}" target="_blank" rel="sponsored nofollow noopener">最新刊の予約・購入 ↗</a></div><h2>📖 全巻・外伝単行本コレクション（タップで各巻の購入ページへ）</h2><p style="font-size:14px;color:var(--text-muted);">第1巻から最新刊、外伝・SS短編集までの表紙コレクションです。画像やボタンをタップすると各巻の楽天Kobo電子書籍ページへ移動します。</p><div class="vol-shelf-grid">\${volumeCards}</div><h2>📺 アニメ・OVA・メディア化・外伝展開データ</h2><div style="background:#fff;padding:20px;border-radius:8px;border:1px solid #d9ddd3;margin:16px 0;"><p style="margin:0;font-size:14px;line-height:1.8;">・<b>TVアニメ化展開</b>：\${escapeXml(book.animeAdaptation || 'アニメ化作品・特大ヒット放送')}<br>・<b>メディアミックス</b>：コミカライズ（漫画版）、CDドラマ、公式外伝SS短編集 展開中<br>・<b>イラスト美術</b>：\${escapeXml(book.illustStyle || '美麗画集・挿絵')}</p></div>\${highlightsList ? \`<h2>✦ ここが面白い！作品の3つの魅力</h2><div class="highlights-box"><ul style="padding-left:18px;margin:0;list-style:none;">\${highlightsList}</ul></div>\` : ''}\${book.firstVolumeStory ? \`<h2>📖 第1話からの基本ストーリー・ここまでの流れ</h2><div class="first-story-box"><p style="margin:0;font-size:15px;line-height:1.9;">\${escapeXml(book.firstVolumeStory)}</p></div>\` : ''}<h2>💡 この作品のあらすじ・見どころ概要</h2><p style="line-height:1.9;font-size:15px;">\${escapeXml(book.description)}</p>\${book.review ? \`<h2>📝 作品の考察・深掘り解説</h2><div class="review-box"><p style="margin:0;">\${escapeXml(book.review)}</p></div>\` : ''}<h2>🎯 こんな読者・気分におすすめ</h2><ul style="line-height:1.9;padding-left:20px;">\${readers}</ul><h2>🏷️ 関連テーマ・タグ</h2><div class="tags">\${tags}</div><h2>📚 似ている作品・関連おすすめ</h2><ul class="related-list">\${relatedCards || '<li>関連作品を準備中です。</li>'}</ul><h2>⚔️ 作品同士の比較</h2><div class="compare-nav-grid">\${compareCards || '<a href="/compare/">比較ページ一覧を見る</a>'}</div></main>`;

const newBody = `<main class="work-detail-main"><div class="wd-top" style="order:1"><div class="crumb"><a href="/">トップ</a>　/　<a href="/works/">作品一覧</a>　/　作品詳細</div><img class="cover-main" src="\${escapeXml(book.cover)}" alt="\${escapeXml(book.title)}の表紙"><div class="eyebrow">WORK GUIDE & REVIEW</div><h1>\${escapeXml(book.title)}</h1><p>作者：<a href="/authors/\${slugify(book.author)}/">\${escapeXml(book.author)}</a>　｜　\${escapeXml(book.genre)}　｜　最新発売日：\${escapeXml(book.salesDate)}</p><p style="font-size:16px;line-height:1.9;color:#3d4841;">\${escapeXml(book.aiIntro || book.description)}</p><a class="cta" href="\${escapeXml(book.affiliateUrl)}" rel="sponsored nofollow noopener" target="_blank">【無料試し読みあり】1巻を楽天Koboで購入 ↗</a><div class="pub-status-box"><div class="pub-status-main"><h3>📢 最新刊・次巻の出版予定日ステータス</h3><p>最新巻：絶賛配信中！ / 次巻（続巻）：<b>2026年秋頃出版予定（公式発表待ち）</b></p></div><a style="background:#d6a24a;color:#17221f;padding:10px 18px;border-radius:4px;font-weight:bold;text-decoration:none;font-size:13px;" href="\${escapeXml(book.affiliateUrl)}" target="_blank" rel="sponsored nofollow noopener">最新刊の予約・購入 ↗</a></div></div><div class="wd-vols" style="order:2"><h2>📖 全巻・外伝単行本コレクション（タップで各巻の購入ページへ）</h2><p style="font-size:14px;color:var(--text-muted);">第1巻から最新刊、外伝・SS短編集までの表紙コレクションです。画像やボタンをタップすると各巻の楽天Kobo電子書籍ページへ移動します。</p><div class="vol-shelf-grid">\${volumeCards}</div></div><div class="wd-rest" style="order:3"><h2>📺 アニメ・OVA・メディア化・外伝展開データ</h2><div style="background:#fff;padding:20px;border-radius:8px;border:1px solid #d9ddd3;margin:16px 0;"><p style="margin:0;font-size:14px;line-height:1.8;">・<b>TVアニメ化展開</b>：\${escapeXml(book.animeAdaptation || 'アニメ化作品・特大ヒット放送')}<br>・<b>メディアミックス</b>：コミカライズ（漫画版）、CDドラマ、公式外伝SS短編集 展開中<br>・<b>イラスト美術</b>：\${escapeXml(book.illustStyle || '美麗画集・挿絵')}</p></div>\${highlightsList ? \`<h2>✦ ここが面白い！作品の3つの魅力</h2><div class="highlights-box"><ul style="padding-left:18px;margin:0;list-style:none;">\${highlightsList}</ul></div>\` : ''}\${book.firstVolumeStory ? \`<h2>📖 第1話からの基本ストーリー・ここまでの流れ</h2><div class="first-story-box"><p style="margin:0;font-size:15px;line-height:1.9;">\${escapeXml(book.firstVolumeStory)}</p></div>\` : ''}<h2>💡 この作品のあらすじ・見どころ概要</h2><p style="line-height:1.9;font-size:15px;">\${escapeXml(book.description)}</p>\${book.review ? \`<h2>📝 作品の考察・深掘り解説</h2><div class="review-box"><p style="margin:0;">\${escapeXml(book.review)}</p></div>\` : ''}<h2>🎯 こんな読者・気分におすすめ</h2><ul style="line-height:1.9;padding-left:20px;">\${readers}</ul><h2>🏷️ 関連テーマ・タグ</h2><div class="tags">\${tags}</div></div><div class="wd-bottom" style="order:4"><h2>📚 似ている作品・関連おすすめ</h2><ul class="related-list">\${relatedCards || '<li>関連作品を準備中です。</li>'}</ul><h2>⚔️ 作品同士の比較</h2><div class="compare-nav-grid">\${compareCards || '<a href="/compare/">比較ページ一覧を見る</a>'}</div></div></main>`;

content = content.replace(oldBody, newBody);

fs.writeFileSync('scripts/fetch-books.mjs', content);
console.log('Patch applied.');
